name: todolist

services:
  db:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_PASSWORD:
      MYSQL_DATABASE: todolist
      MYSQL_USER: todolist
    restart: always
    volumes:
      - ./todolist.sql:/docker-entrypoint-initdb.d/todolist.sql:ro
      - "db_data:/var/lib/mysql"
  app:
    build: .
    image: todolist/app:8.3.0
    depends_on: 
      - db
    environment:
      TODOLIST_DB_HOST: db
      TODOLIST_DB_PASS:
    restart: always
  rp:
    image: nginx:1.25-alpine3.18-perl
    ports: 
      - 12000:80
    depends_on: 
      - app
      - db
    restart: always
    volumes: 
      - ./site.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  db_data: